version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8000" # Changed host port to 8001
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://nexcell:password@db:5432/nexcell_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=nexcell
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nexcell_db
    ports:
      - "5433:5432" # Changed host port to 5433
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379" # Changed host port to 6380
    volumes:
      - redis_data_new:/data

volumes:
  postgres_data_new:
  redis_data_new: